import localFont from "next/font/local";
import "./globals.css";

const cabinet = localFont({
  src: "./fonts/CabinetGrotesk.woff",
  display: "swap",
  variable: '--font-cabinet',
})

const satoshi = localFont({
  src: "./fonts/SatoshiMedium.woff",
  display: "swap",
  variable: '--font-satoshi',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cabinet.variable} ${satoshi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
